services:
  api:
    container_name: api
    image: basic-web-app
    build:
      context: .
      dockerfile: .docker/Containerfile
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-heroes_api}
    ports:
      - '8000:80'
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend

  db:
    container_name: db
    image: postgres:18.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-heroes_api}
      TZ: Europe/Zurich
      PGTZ: Europe/Zurich
    volumes:
      - python-database:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - backend
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    environment:
      # Required by pgAdmin
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@domain.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

      # Don't require the user to login
      PGADMIN_CONFIG_SERVER_MODE: "False"

      # Don't require a "master" password after logging in
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    networks:
      - backend

volumes:
  python-database:

networks:
  backend:
